const $=id=>document.getElementById(id); const cfg=window.LUKINHA_SUPABASE||{}; const hasSB=!!(cfg.url&&cfg.anonKey&&window.supabase); const sb=hasSB?window.supabase.createClient(cfg.url,cfg.anonKey):null;
const defaults={heroTitle:'Muito mais que música. É encontro.',heroKicker:'PAGODE • ENERGIA • RESENHA',aboutTitle:'O LUKINHA',aboutText:'Espaço preparado para receber a biografia oficial de Lucas Vaz, sua história, trajetória e a identidade do Pagode do Lukinha.',aboutImage:'assets/agenda-bg.jpg',contactName:'Carrapicho',contactWhatsapp:'5516981010940',contactInstagram:'https://www.instagram.com/cantorlucasvaz/',contactMessage:'Olá, Carrapicho! Vim pelo site oficial do Pagode do Lukinha e gostaria de informações para contratação de show.'};
let editShow=null,editVideo=null,settings={...defaults};
function localGet(k,d=[]){try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}} function localSet(k,v){localStorage.setItem(k,JSON.stringify(v))}
function showApp(){ $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('modeLabel').textContent=hasSB?'Supabase conectado':'Modo local';$('supabaseStatus').textContent=hasSB?'Conectado ao Supabase':'Não configurado — usando armazenamento local';loadAll() }
async function authInit(){if(hasSB){const {data}=await sb.auth.getSession();if(data.session)return showApp()} const ok=sessionStorage.getItem('lukinha_admin_local')==='1';if(ok)showApp()}
$('loginBtn').onclick=async()=>{const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(hasSB){const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginMsg').textContent=error.message;return}showApp()}else if(email==='admin@lukinha.local'&&password==='lukinha'){sessionStorage.setItem('lukinha_admin_local','1');showApp()}else $('loginMsg').textContent='Login local inválido.'};
$('logoutBtn').onclick=async()=>{if(hasSB)await sb.auth.signOut();sessionStorage.removeItem('lukinha_admin_local');location.reload()};
document.querySelectorAll('#adminNav button').forEach(b=>b.onclick=()=>go(b.dataset.tab));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));function go(id){document.querySelectorAll('#adminNav button,.panel').forEach(x=>x.classList.remove('active'));document.querySelector(`#adminNav button[data-tab="${id}"]`)?.classList.add('active');$(id).classList.add('active');$('pageTitle').textContent=document.querySelector(`#adminNav button[data-tab="${id}"]`)?.textContent||id}
async function getShows(){if(hasSB){const {data}=await sb.from('shows').select('*').order('show_date');return data||[]}return localGet('lukinha_shows_v12',[])} async function putShow(obj){if(hasSB){if(editShow)await sb.from('shows').update(obj).eq('id',editShow);else await sb.from('shows').insert(obj)}else{let a=await getShows();if(editShow){const i=a.findIndex(x=>x.id===editShow);a[i]={...a[i],...obj}}else a.push({...obj,id:Date.now()});localSet('lukinha_shows_v12',a)}} async function removeShow(id){if(!confirm('Excluir este show?'))return;if(hasSB)await sb.from('shows').delete().eq('id',id);else localSet('lukinha_shows_v12',(await getShows()).filter(x=>x.id!==id));renderShows()}
function dateLabel(s){if(!s.show_date)return '—';return new Date(s.show_date+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','').toUpperCase()} async function renderShows(){const a=await getShows();$('statShows').textContent=a.length;$('statNext').textContent=a[0]?`${dateLabel(a[0])} · ${a[0].city}`:'—';const html=a.map(s=>`<div class="list-item"><div><h3>${dateLabel(s)} · ${s.city||''}${s.state?' — '+s.state:''}</h3><p>${s.event_name||''}${s.place?' · '+s.place:''}</p></div><div class="item-actions"><button class="secondary" onclick="editShowItem(${s.id})">Editar</button><button class="danger" onclick="removeShow(${s.id})">Excluir</button></div></div>`).join('')||'<p class="muted">Nenhum show cadastrado.</p>';$('showList').innerHTML=html;$('dashShows').innerHTML=html}
window.editShowItem=async id=>{const s=(await getShows()).find(x=>x.id===id);if(!s)return;editShow=id;$('showDate').value=s.show_date||'';$('showTime').value=(s.show_time||'').slice(0,5);$('showCity').value=s.city||'';$('showState').value=s.state||'';$('showEvent').value=s.event_name||'';$('showPlace').value=s.place||'';$('showTicket').value=s.ticket_url||'';$('saveShow').textContent='Salvar show';$('cancelShow').classList.remove('hidden');go('agenda')}; window.removeShow=removeShow;
$('saveShow').onclick=async()=>{if(!$('showDate').value||!$('showCity').value.trim())return alert('Preencha data e cidade.');await putShow({show_date:$('showDate').value,show_time:$('showTime').value||null,city:$('showCity').value.trim(),state:$('showState').value.trim().toUpperCase(),event_name:$('showEvent').value.trim(),place:$('showPlace').value.trim(),ticket_url:$('showTicket').value.trim(),published:true});resetShow();renderShows()};function resetShow(){editShow=null;['showDate','showTime','showCity','showState','showEvent','showPlace','showTicket'].forEach(id=>$(id).value='');$('saveShow').textContent='Publicar show';$('cancelShow').classList.add('hidden')}$('cancelShow').onclick=resetShow;
async function getVideos(){if(hasSB){const {data}=await sb.from('videos').select('*').order('sort_order').order('created_at');return data||[]}return localGet('lukinha_videos_v12',[]).sort((a,b)=>(a.sort_order??999999)-(b.sort_order??999999))}
async function putVideo(obj){if(hasSB){if(editVideo)await sb.from('videos').update(obj).eq('id',editVideo);else{const current=await getVideos();await sb.from('videos').insert({...obj,sort_order:current.length})}}else{let a=await getVideos();if(editVideo){const i=a.findIndex(x=>String(x.id)===String(editVideo));a[i]={...a[i],...obj}}else a.push({...obj,id:Date.now(),sort_order:a.length});localSet('lukinha_videos_v12',a)}}
async function removeVideo(id){if(!confirm('Excluir este vídeo?'))return;if(hasSB)await sb.from('videos').delete().eq('id',id);else localSet('lukinha_videos_v12',(await getVideos()).filter(x=>String(x.id)!==String(id)));await normalizeVideoOrder();renderVideos()}
async function normalizeVideoOrder(){const a=await getVideos();if(hasSB){await Promise.all(a.map((v,i)=>sb.from('videos').update({sort_order:i}).eq('id',v.id)))}else{a.forEach((v,i)=>v.sort_order=i);localSet('lukinha_videos_v12',a)}}
let videoSortable=null;
function initVideoSortable(){const el=$('videoList');if(!el||!window.Sortable)return;if(videoSortable)videoSortable.destroy();videoSortable=Sortable.create(el,{animation:180,handle:'.drag-handle',ghostClass:'sortable-ghost',chosenClass:'sortable-chosen',dragClass:'sortable-drag',delay:120,delayOnTouchOnly:true,touchStartThreshold:4,onEnd:async()=>{const ids=[...el.querySelectorAll('.list-item[data-video-id]')].map(x=>x.dataset.videoId);el.classList.add('order-saving');try{if(hasSB){await Promise.all(ids.map((id,i)=>sb.from('videos').update({sort_order:i}).eq('id',id)))}else{const all=await getVideos();const byId=new Map(all.map(v=>[String(v.id),v]));const ordered=ids.map((id,i)=>({...byId.get(String(id)),sort_order:i})).filter(Boolean);localSet('lukinha_videos_v12',ordered)} }finally{el.classList.remove('order-saving')}}})}
async function renderVideos(){const a=await getVideos();$('statVideos').textContent=a.length;$('videoList').innerHTML=a.map(v=>`<div class="list-item" data-video-id="${v.id}"><button class="drag-handle" type="button" aria-label="Arrastar ${v.title||'vídeo'}" title="Arraste para reordenar">☰</button><div><h3>${v.title||'Sem título'}</h3><p>${v.youtube_url}</p></div><div class="item-actions"><button class="secondary" onclick="editVideoItem(${v.id})">Editar</button><button class="danger" onclick="removeVideo(${v.id})">Excluir</button></div></div>`).join('')||'<p class="muted">Nenhum vídeo cadastrado.</p>';initVideoSortable()}
window.editVideoItem=async id=>{const v=(await getVideos()).find(x=>x.id===id);editVideo=id;$('videoTitle').value=v.title||'';$('videoUrl').value=v.youtube_url||'';$('videoDescription').value=v.description||'';$('saveVideo').textContent='Salvar vídeo';$('cancelVideo').classList.remove('hidden');go('videos')};window.removeVideo=removeVideo;$('saveVideo').onclick=async()=>{if(!$('videoUrl').value.trim())return alert('Cole o link do YouTube.');await putVideo({title:$('videoTitle').value.trim(),youtube_url:$('videoUrl').value.trim(),description:$('videoDescription').value.trim(),published:true});resetVideo();renderVideos()};function resetVideo(){editVideo=null;['videoTitle','videoUrl','videoDescription'].forEach(id=>$(id).value='');$('saveVideo').textContent='Publicar vídeo';$('cancelVideo').classList.add('hidden')}$('cancelVideo').onclick=resetVideo;
async function loadSettings(){if(hasSB){const {data}=await sb.from('site_settings').select('data').eq('id','main').maybeSingle();settings={...defaults,...(data?.data||{})}}else settings={...defaults,...localGet('lukinha_settings_v12',{})};$('heroTitle').value=settings.heroTitle;$('heroKicker').value=settings.heroKicker;$('aboutTitle').value=settings.aboutTitle;$('aboutText').value=settings.aboutText;$('aboutImage').value=settings.aboutImage;$('contactName').value=settings.contactName;$('contactWhatsapp').value=settings.contactWhatsapp;$('contactMessage').value=settings.contactMessage;$('contactInstagram').value=settings.contactInstagram}async function saveSettings(){if(hasSB)await sb.from('site_settings').upsert({id:'main',data:settings,updated_at:new Date().toISOString()});else localSet('lukinha_settings_v12',settings);alert('Alterações salvas.')} $('saveHome').onclick=()=>{settings.heroTitle=$('heroTitle').value;settings.heroKicker=$('heroKicker').value;saveSettings()};$('saveAbout').onclick=()=>{settings.aboutTitle=$('aboutTitle').value;settings.aboutText=$('aboutText').value;settings.aboutImage=$('aboutImage').value;saveSettings()};$('saveContact').onclick=()=>{settings.contactName=$('contactName').value;settings.contactWhatsapp=$('contactWhatsapp').value;settings.contactMessage=$('contactMessage').value;settings.contactInstagram=$('contactInstagram').value;saveSettings()};async function loadAll(){await Promise.all([loadSettings(),renderShows(),renderVideos()])}authInit();
