const seedShows=[{date:'28 SET',city:'SÃO CARLOS — SP',event:'Nome do evento',place:'Local do evento',time:'20h',ticket:'#'},{date:'05 OUT',city:'RIBEIRÃO PRETO — SP',event:'Nome do evento',place:'Local do evento',time:'20h',ticket:'#'},{date:'12 OUT',city:'ARARAQUARA — SP',event:'Nome do evento',place:'Local do evento',time:'20h',ticket:'#'}];
const shows=JSON.parse(localStorage.getItem('lukinha_shows')||'null')||seedShows;const root=document.querySelector('#shows');root.innerHTML=shows.map((s,i)=>`<article class="show" style="transition-delay:${i*.09}s"><div class="show-head"><div class="date">${s.date}</div><div class="city">${s.city}</div><div class="plus">+</div></div><div class="details"><h3>${s.event||''}</h3><p>${s.place||''}${s.time?' • '+s.time:''}</p>${s.ticket&&s.ticket!=='#'?`<a class="btn" href="${s.ticket}" target="_blank">Comprar ingresso</a>`:''}</div></article>`).join('');document.querySelectorAll('.show-head').forEach(h=>h.onclick=()=>{const a=h.parentElement;document.querySelectorAll('.show.open').forEach(x=>x!==a&&x.classList.remove('open'));a.classList.toggle('open')});
function ytId(url){const m=String(url||'').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{6,})/);return m?m[1]:''}
const videoSeed=[{title:'Vídeo em destaque',description:'Cadastre no admin o link e a descrição de um vídeo oficial do YouTube.',url:''}];
const videos=JSON.parse(localStorage.getItem('lukinha_videos')||'null')||videoSeed;
const vg=document.querySelector('#videoGrid');
const valid=videos.filter(v=>v.url&&ytId(v.url));
vg.innerHTML=valid.length?valid.map(v=>{const id=ytId(v.url);return `<article class="video-card"><div class="video-frame" data-youtube="${id}" role="button" tabindex="0" aria-label="Reproduzir ${v.title||'vídeo'}"><img class="video-thumb" src="https://i.ytimg.com/vi/${id}/hqdefault.jpg" alt="${v.title||'Vídeo Pagode do Lukinha'}" loading="lazy"><span class="video-play">▶</span></div><div class="video-copy"><h3>${v.title||'Vídeo'}</h3><p>${v.description||''}</p></div></article>`}).join(''):`<div class="empty">Os vídeos cadastrados no painel administrativo aparecerão aqui.</div>`;
function playVideo(frame){const id=frame.dataset.youtube;if(!id)return;frame.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${id}?autoplay=1" title="Vídeo Pagode do Lukinha" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`}
document.querySelectorAll('.video-frame[data-youtube]').forEach(frame=>{frame.addEventListener('click',()=>playVideo(frame));frame.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();playVideo(frame)}})});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
