-- Pagode do Lukinha — schema idempotente
-- Pode ser executado novamente sem apagar dados existentes.

create table if not exists public.site_settings (
  id text primary key default 'main',
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.shows (
  id bigint generated by default as identity primary key,
  show_date date not null,
  show_time time,
  city text not null,
  state text,
  event_name text,
  place text,
  ticket_url text,
  published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text,
  youtube_url text not null,
  description text,
  published boolean default true,
  sort_order int default 0,
  created_at timestamptz default now()
);

-- Garante colunas necessárias mesmo se as tabelas já existiam em versão anterior.
alter table public.site_settings add column if not exists data jsonb not null default '{}'::jsonb;
alter table public.site_settings add column if not exists updated_at timestamptz default now();

alter table public.shows add column if not exists show_date date;
alter table public.shows add column if not exists show_time time;
alter table public.shows add column if not exists city text;
alter table public.shows add column if not exists state text;
alter table public.shows add column if not exists event_name text;
alter table public.shows add column if not exists place text;
alter table public.shows add column if not exists ticket_url text;
alter table public.shows add column if not exists published boolean default true;
alter table public.shows add column if not exists created_at timestamptz default now();

alter table public.videos add column if not exists title text;
alter table public.videos add column if not exists youtube_url text;
alter table public.videos add column if not exists description text;
alter table public.videos add column if not exists published boolean default true;
alter table public.videos add column if not exists sort_order int default 0;
alter table public.videos add column if not exists created_at timestamptz default now();

alter table public.site_settings enable row level security;
alter table public.shows enable row level security;
alter table public.videos enable row level security;

-- PostgreSQL não possui CREATE POLICY IF NOT EXISTS.
-- Estes blocos só criam cada policy quando ela ainda não existe.
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='site_settings' and policyname='public read settings') then
    create policy "public read settings" on public.site_settings for select to anon, authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='shows' and policyname='public read shows') then
    create policy "public read shows" on public.shows for select to anon, authenticated using (published = true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='videos' and policyname='public read videos') then
    create policy "public read videos" on public.videos for select to anon, authenticated using (published = true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='site_settings' and policyname='auth manage settings') then
    create policy "auth manage settings" on public.site_settings for all to authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='shows' and policyname='auth manage shows') then
    create policy "auth manage shows" on public.shows for all to authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='videos' and policyname='auth manage videos') then
    create policy "auth manage videos" on public.videos for all to authenticated using (true) with check (true);
  end if;
end $$;

insert into public.site_settings (id, data)
values (
  'main',
  '{"heroTitle":"Muito mais que música. É encontro.","heroKicker":"PAGODE • ENERGIA • RESENHA","aboutTitle":"O LUKINHA","aboutText":"Espaço preparado para receber a biografia oficial de Lucas Vaz, sua história, trajetória e a identidade do Pagode do Lukinha.","aboutImage":"assets/agenda-bg.jpg","contactName":"Carrapicho","contactWhatsapp":"5516981010940","contactInstagram":"https://www.instagram.com/cantorlucasvaz/","contactMessage":"Olá, Carrapicho! Vim pelo site oficial do Pagode do Lukinha e gostaria de informações para contratação de show."}'::jsonb
)
on conflict (id) do nothing;
